date/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('myweb.urls')),  # 默认访问的登录界面
    path('myadmin/', include('myadmin.urls')),  # 后台管理

]

myweb/urls.py
# 前端子路由配置
from django.urls import path

from myweb.views import index
from myweb.views import home
urlpatterns = [
    path('', index.index, name="myweb_index"),
    path('index/login' , index.login , name="myweb_index_login") ,
    path('index/register',index.register,name="myweb_index_register"),#注册
    path('index/insert',index.insert,name="myweb_index_insert"),#执行注册
    path('index/dologin' , index.dologin , name="myweb_index_dologin") ,
    path('index/logout' , index.logout , name="myweb_index_logout") ,
    path('index/verify' , index.verify , name="myweb_index_verify") ,  # 验证码
    #主页面
    path('home',home.home,name='myweb_home'),
    #文章展示页面
    path('home/article/<int:aid>',home.article,name="myweb_home_article"),
    #发布文章页面
    path('home/addarticle',home.addarticle,name="myweb_home_addarticle"),
    #文章删除
    path('article_del',home.article_del,name="article_del"),
    #点赞
    path('aup',home.aup,name="aup"),
    #收藏
    path('collect',home.collect,name="collect"),
    #取消收藏
    path('c_del',home.c_del,name="c_del"),
    #收藏展示页面
    path('home/collection/<int:wid>',home.collection,name="myweb_home_collection"),
    #发表评论
    path('commit',home.commit,name="commit"),
    #删除评论
    path('del_commit',home.del_commit,name="del_commit"),
    #执行添加文章
    path('home/insertarticle',home.insertarticle,name="myweb_home_insertarticle"),
    #个人页面展示
    path('home/persional/<int:wid>',home.persional,name="myweb_home_persional"),
    #分类主页面
    path('home/cat/<int:wid>',home.cat,name="myweb_home_cat"),
    #个人信息页面
    path('home/edit',home.edit,name="myweb_home_edit"),
    #执行编辑
    path('home/update/<int:wid>',home.update,name="myweb_home_update"),
    # 个人简介
    path('home/editinfo' , home.editinfo , name="myweb_home_editinfo") ,
    # 执行编辑简介内容
    path('home/updateinfo/<int:wid>' , home.updateinfo , name="myweb_home_updateinfo") ,

]

myadmin/models.py
from datetime import datetime

from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
  #用户账号信息模型

class User(models.Model):
    username = models.CharField(max_length=50)    #用户账号
    nickname = models.CharField(max_length=50)    #昵称
    password_hash = models.CharField(max_length=100)  #密码
    password_salt = models.CharField(max_length=50)    #密码干扰值
    status = models.IntegerField(default=1)    #状态:1正常/6.管理员/2禁用/9删除
    create_at = models.DateTimeField(default=datetime.now)    #创建时间
    update_at = models.DateTimeField(default=datetime.now)    #修改时间

    def toDict(self):
        return {'id':self.id,'username':self.username,'nickname':self.nickname,'password_hash':self.password_hash,'password_salt':self.password_salt,'status':self.status,'create_at':self.create_at.strftime('%Y-%m-%d %H:%M:%S'),'update_at':self.update_at.strftime('%Y-%m-%d %H:%M:%S')}

    class Meta:
        db_table = "user"  # 表名

class Blog(models.Model):
    nid=models.AutoField(primary_key=True)
    title=models.CharField(max_length=64)
    site_name=models.CharField(max_length=32)
    theme=models.CharField(max_length=64)
    def toDict(self):
        return {'title':self.title}
    class Meta:
        db_table="blog"

#分类表
class Category(models.Model):
    nid = models.AutoField(primary_key=True)
    title=models.CharField(max_length=64)
    blog=models.ForeignKey(to=Blog,to_field='nid',null=True,on_delete=models.CASCADE)
    def toDict(self):
        return {'title':self.title}
    class Meta:
        db_table="category"
#标签
class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title=models.CharField(max_length=64)
    blog=models.ForeignKey(to=Blog,to_field='nid',null=True,on_delete=models.CASCADE)
    def toDict(self):
        return {'title':self.title}
    class Meta:
        db_table = "tag"  # 更改表名
#前端用户信息表
class Webuser(models.Model):
    nickname = models.CharField(max_length=50)
    head = models.CharField(max_length=255)
    mobile = models.CharField(max_length=50)
    password = models.CharField(max_length=50,null=True,blank=True)
    email = models.CharField(max_length=50)
    status = models.IntegerField(default=1)
    blog = models.OneToOneField(to=Blog,to_field='nid',null=True,on_delete=models.CASCADE)
    create_at = models.DateTimeField(default=datetime.now)
    update_at = models.DateTimeField(default=datetime.now)

    def toDict(self):
        return {'id':self.id,'blog':self.blog,'nickname':self.nickname,'head':self.head,'mobile':self.mobile,'head':self.head,'password':self.password,'status':self.status,'create_at':self.create_at.strftime('%Y-%m-%d %H:%M:%S'),'update_at':self.update_at.strftime('%Y-%m-%d %H:%M:%S')}

    class Meta:
        db_table = "webuser"  # 更改表名

#文章信息模型
class Article(models.Model):
    name = models.CharField(max_length=255)        #文章名称
    picture = models.CharField(max_length=255)  #封面图片
    main = models.CharField(max_length=255,null=True,blank=True)   #主要内容
    message = models.TextField()    #文章内容
    title = models.CharField(max_length=255)    #话题
    title_id = models.CharField(max_length=255)    #话题编号
    status = models.IntegerField(default=1)        #状态:1正常/2暂停/3删除
    publish_at = models.DateTimeField(default=datetime.now)    #发布时间
    up_num = models.IntegerField(default=0)                   #点赞数
    down_num = models.IntegerField(default=0)                     #收藏数
    blog = models.ForeignKey(to=Blog,to_field='nid',null=True,on_delete=models.CASCADE)
    category = models.ForeignKey(to=Category,to_field='nid',null=True,on_delete=models.CASCADE)
    tag = models.ManyToManyField(to=Tag , through='ArticleTOTag' , through_fields=('article','tag'))
    def toDict(self):
        articlename = self.name.split("-")
        return {'id':self.id,'name':articlename[0],'blog':self.blog,'category':self.category,'tag':self.tag,'picture':self.picture,'message':self.message,'title':self.title,'title_id':self.title_id,'status':self.status,'publish_at':self.publish_at.strftime('%Y-%m-%d %H:%M:%S'),'up_num':self.up_num,'webuser':self.webuser}

    class Meta:
        db_table = "article"  # 表名

class ArticleTOTag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to=Article,to_field='id',on_delete=models.CASCADE)
    tag = models.ForeignKey(to=Tag,to_field='nid',on_delete=models.CASCADE)


class Commit(models.Model):
    nid = models.AutoField(primary_key=True)
    webuser = models.ForeignKey(to='Webuser' , to_field='id',on_delete=models.CASCADE)
    article = models.ForeignKey(to='Article' , to_field='id',on_delete=models.CASCADE)
    content = models.CharField(max_length=255)
    publish_at = models.DateTimeField(default=datetime.now)
    parent = models.ForeignKey(to='self',to_field='nid',on_delete=models.CASCADE,null=True,blank=True)
    class Meta:
        db_table = "commit"  # 更改表名
#点赞
class UpAndDown(models.Model):
    nid = models.AutoField(primary_key=True)
    webuser = models.ForeignKey(to=Webuser,to_field='id',on_delete=models.CASCADE)
    article = models.ForeignKey(to=Article,to_field='id',on_delete=models.CASCADE)
    up_down = models.BooleanField()

    class Meta:
        unique_together=(("webuser","article"),)   #联合

#收藏
class Collect(models.Model):
    nid = models.AutoField(primary_key=True)
    webuser = models.ForeignKey(to=Webuser,to_field='id',on_delete=models.CASCADE)
    article = models.ForeignKey(to=Article,to_field='id',on_delete=models.CASCADE)
    up_down = models.BooleanField()

    class Meta:
        unique_together=(("webuser","article"),)   #联合

#个人简介及信息表
class Info(models.Model):
    id = models.AutoField(primary_key=True)
    webuser = models.ForeignKey(to='Webuser' , to_field='id' , on_delete=models.CASCADE)
    info = models.CharField(max_length=255)
    star = models.CharField(max_length=50)
    birth = models.DateTimeField(max_length=50,null=True)
    habit = models.CharField(max_length=255)
    school = models.CharField(max_length=127)
    location = models.CharField(max_length=127)

    class Meta:
        db_table = "info"  # 更改表名

myweb/views/home.py
from myweb.views import index
from django.db.models import Q , F
from django.http import HttpResponse
from django.shortcuts import render , redirect
from django.urls import reverse
import time
from datetime import datetime
from myadmin.models import Article , Category , Blog , Commit , UpAndDown , Collect , Webuser , Info
from django.utils import timezone as datetime
#主页显示
def home(request):
    amod = Article.objects.get_queryset().order_by('-up_num')
    mywhere = []
    alist = amod.filter(status__lt=3)
    # 获取、判断并封装关keyword键搜索
    kw = request.GET.get("keyword" , None)
    if kw:
        # 查询
        alist = alist.filter(Q(name__contains=kw) | Q(category__title__contains=kw) | Q(blog__webuser__nickname__contains=kw))
        mywhere.append("keyword=" + kw)
    # 获取、判断并封装状态status搜索条件
    status = request.GET.get('status' , '')
    if status != '':
        alist = alist.filter(status=status)
        mywhere.append("status=" + status)
    context = {"articlelist": alist ,'mywhere': mywhere}
    return render(request , 'myweb/home/home.html' , context)
    #用户浏览文章
def article(request,aid):
    article = Article.objects.get(id=aid)
    commit_list = article.commit_set.all()
    context = {'article':article,'commit_list':commit_list}
    return render(request,'myweb/home/article.html',context)

    #用户发布文章
def addarticle(request):
    ctype = Category.objects.all()
    btype = Blog.objects.all()
    context = {"ctype": ctype , "btype": btype}
    return render(request , 'myweb/home/addarticle.html' , context)

    #执行发布文章
def insertarticle(request):
    '''执行添加'''
    try:
        blog_id = request.session.session_key
        # 上传图片操作
        # 图片的上传处理
        myfile = request.FILES.get("picture" , None)
        if not myfile:
            return HttpResponse("没有封面上传文件信息")
        picture = str(time.time()) + "." + myfile.name.split('.').pop()
        destination = open("./static/uploads/article/" + picture , "wb+")
        for chunk in myfile.chunks():  # 分块写入文件
            destination.write(chunk)
        destination.close()
        message = request.POST.get('message')
        from bs4 import BeautifulSoup   #处理xss攻击
        soup = BeautifulSoup(message,'html.parser') #过滤掉了html
        tags = soup.find_all()
        for tag in tags:
            if tag.name == 'script':
                tag.decompose()
        # 封装
        ob = Article()
        ob.message = str(soup)
        ob.picture = picture
        ob.name = request.POST['name']
        ob.main = request.POST['main']
        ob.blog_id = request.POST['blog']
        ob.category_id = request.POST['category']
        ob.status = 1
        ob.publish_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ob.save()
        return redirect(reverse('myweb_home'))
    except Exception as err:
        print(err)
        context = {"info": "添加失败"}
    return render(request , "myadmin/info.html" , context)

    #发布评论
def commit(request):
    try:
        ob = Commit()
        ob.article_id = request.POST.get('article_id')
        ob.webuser_id = request.POST.get('webuser_id')
        ob.content = request.POST.get('content')
        ob.parent_id = request.POST.get('parent_id')
        ob.save()
        context = {'info':'发布成功'}
    except Exception as err:
        print(err)
        context = {"info": "发布失败"}
    return render(request, "myadmin/info.html" , context)

#删除文章
def article_del(request):
    nid = request.POST.get('article_id')
    try:
        ob = Article.objects.get(id=nid)
        ob.delete()
        context = {"info": "删除成功！"}
    except Exception as err:
        print(err)
        context = {"info": "删除失败"}
    return render(request , "myadmin/info.html" , context)

#删除评论
def del_commit(request):
    nid = request.POST.get('del_id')
    try:
        ob = Commit.objects.get(nid=nid)
        ob.delete()
        context = {"info": "删除成功！"}
    except Exception as err:
        print(err)
        context = {"info": "删除失败"}
    return render(request , "myadmin/info.html" , context)

    #点赞
def aup(request):
    webuser_id = request.POST.get('webuser_id')
    article_id = request.POST.get('article_id')
    up = UpAndDown.objects.filter(webuser_id=webuser_id,article_id=article_id).first()
    if up:
        context = {"info": "已经点过了"}
    else:
        ob = UpAndDown()
        ob.article_id = article_id
        ob.webuser_id = webuser_id
        ob.up_down = request.POST.get('up_num')
        ob.save()
        Article.objects.filter(id=article_id).update(up_num=F('up_num')+1)
        context = {"info": "点赞成功"}
    return render(request , "myadmin/info.html" , context)

#收藏功能
def collect(request):
    webuser_id = request.POST.get('webuser_id')
    article_id = request.POST.get('article_id')
    col = Collect.objects.filter(webuser_id=webuser_id,article_id=article_id).first()
    if col:
        context = {"info": "已经点过了"}
    else:
        ob = Collect()
        ob.article_id = article_id
        ob.webuser_id = webuser_id
        ob.up_down = request.POST.get('up_num')
        ob.save()
        Article.objects.filter(id=article_id).update(down_num=F('down_num')+1)
        context = {"info": "收藏成功"}
    return render(request , "myadmin/info.html" , context)

#取消收藏
def c_del(request):
    nid = request.POST.get('collect_nid')
    article_id = request.POST.get('article_id')
    try:
        ob = Collect.objects.get(nid=nid)
        ob.delete()
        Article.objects.filter(id=article_id).update(down_num=F('down_num') - 1)
        context = {"info": "取消成功！"}
    except Exception as err:
        print(err)
        context = {"info": "取消失败"}
    return render(request , "myadmin/info.html" , context)

#个人页面展示
def persional(request,wid):
    webuser = Webuser.objects.filter(id=wid).first()
    info = Info.objects.filter(webuser_id=wid).first()
    if not webuser:
        return render(request,'error.html')
    blog = webuser.blog
    #获得该论坛下的所有文章
    article_list = blog.article_set.all().order_by('publish_at')
    context = {"alist":article_list,"blog":blog,"info":info}
    return render(request,"myweb/home/persional.html",context)

#展示收藏文章
def collection(request,wid):
    webuser = Webuser.objects.filter(id=wid).first()
    info = Info.objects.filter(webuser_id=wid).first()
    collect = Collect.objects.filter(webuser_id=wid)
    if not collect:
        context = {"啥也没有"}
    blog = webuser.blog
    #获得该论坛收藏的所有文章
    article_list = Article.objects.all().order_by('-up_num')
    context = {"alist":article_list,"collect":collect,"blog":blog,"info":info}
    return render(request,"myweb/home/collection.html",context)

#分类页面展示
def cat(request,wid):
    cat = Category.objects.filter(nid=wid).first()
    if not cat:
        context = {"啥也没有"}
    # 获得该论坛收藏的所有文章
    if not cat.article_set.all():
        context={"啥也没有"}
    #取数据判断其状态、排序
    article_list = cat.article_set.filter(status__lt=2).all().order_by('-up_num')
    context = {"alist": article_list,"cat":cat.title}
    return render(request,'myweb/home/cat.html',context)

#编辑个人信息页面
def edit(request):
    return render(request,'myweb/home/edit.html')

#执行编辑信息
def update(request,wid):
    '''执行编辑信息'''
    myfile = request.FILES.get("head" , None)
    if not myfile:
        return HttpResponse("没有封面上传文件信息")
    head = str(time.time()) + "." + myfile.name.split('.').pop()
    destination = open("./static/uploads/webuser/" + head , "wb+")
    for chunk in myfile.chunks():  # 分块写入文件
        destination.write(chunk)
    destination.close()
    try:
        ob = Webuser.objects.get(id=wid)
        ob.nickname = request.POST['nickname']
        ob.mobile = request.POST['mobile']
        ob.password = request.POST['password']
        ob.head = head
        ob.update_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        bid = ob.blog.nid
        ob.save()
        obj = Blog.objects.get(nid=bid)
        obj.title = request.POST['blog']
        context = {"log": "修改成功！"}
        return redirect(reverse('myweb_home_edit'),context)
    except Exception as err:
        print(err)
        context = {"log": "修改失败"}
    return render(request , "myweb/log.html" , context)
#编辑简介页面
def editinfo(request):
    return render(request,"myweb/home/editinfo.html")

#执行编辑简介
def updateinfo(request,wid):
    #判断表是否存在
    try:
        ob = Info.objects.get(webuser_id=wid)
        ob.info = request.POST['info']
        ob.habit = request.POST['habit']
        ob.star = request.POST['star']
        ob.birth = request.POST['birth']
        ob.school = request.POST['school']
        ob.location = request.POST['location']
        ob.save()
        context = {"info": "修改成功"}
        return redirect(reverse('myweb_home_editinfo'))
    except Exception as err:
        print(err)
        context = {"info": "修改失败"}
    return render(request , "myadmin/info.html" , context)

templates/myweb/index/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>交友论坛首页</title>
    <meta name="description" content="前端首页展示，包括登录、注册"/>
    <meta name="keywords" content="交友论坛"/>
    <link rel="stylesheet" href="{% static 'myweb/index/css/index.css' %}">
</head>
<body>
<header style="position: relative;
  width: 100%;
  height: 560px;" id="header">
    <div style="width: 100%;
  height: 560px;
  background: url('/static/banckground/1.jpg') no-repeat fixed center 0;
  background-attachment: fixed;"></div>
    <div style="color:rgba(236,229,87,0.91);position: absolute;top: 140px;left: 50%;font-size: 50px;width: 558px;margin-left: -279px;">
        <p class="index-tex">登录、注册后进入论坛</p>
    </div>
</header>
<div class="main">
    <div class="main-inner">
        <div class="main-list">
            <div class="recommend-line">
                <span>大家正在关注</span>
            </div>
            <div class="main-list__wrapper clearfix">
                <a href="#"><img src="{% static 'myweb/index/images/cont/main-list__img1.jpg' %}"
                                 alt="#"><span>旅游</span></a>
                <a href="#"><img src="{% static 'myweb/index/images/cont/main-list__img2.jpg' %}"
                                 alt="#"><span>艺术</span></a>
                <a href="#"><img src="{% static 'myweb/index/images/cont/main-list__img3.jpg' %}"
                                 alt="#"><span>运动</span></a>
                <a href="#"><img src="{% static 'myweb/index/images/cont/main-list__img4.jpg' %}"
                                 alt="#"><span>读书</span></a>
                <a href="#"><img src="{% static 'myweb/index/images/cont/main-list__img5.jpg' %}"
                                 alt="#"><span>乐器</span></a>
                <a href="#"><img src="{% static 'myweb/index/images/cont/main-list__img6.jpg' %}"
                                 alt="#"><span>拍照</span></a>
                <a href="#"><img src="{% static 'myweb/index/images/cont/main-list__img7.jpg' %}"
                                 alt="#"><span>游戏</span></a>
            </div>
        </div>
        <div class="main-waterfall">
            <div class="recommend-line">
                <span>站内热文</span>
            </div>
            <div class="main-waterfall__wrapper">
                <div class="main-waterfall__row clearfix">
                    <div class="waterfall-imgbox waterfall-box"><a href="#"><img
                            src="{% static 'myweb/index/images/cont/waterfall_imgA.jpg' %}" alt="#"></a></div>
                    <div class="waterfall-box">
                        <div class="waterfall-info waterfall-info__top">
                            <h3><a href="#">最新科技咨询</a></h3>
                            <span>国家知识产权分析评议服务示范创建机构,背靠中国科学院科研仪器设备、科技成果和专家人才资源,综合应用科技</span><br>
                            <span>来自<a href="#">admin</a></span>
                            <i class="info-arrow info-arrow__left"></i>
                        </div>
                        <div class="waterfall-info waterfall-info__bom">
                            <h3><a href="#">中国古代乐器《一弦琴》</a></h3>
                            <span>古琴的一种。 晋 王嘉 《拾遗记·殷汤》</span><br>
                            <span>来自<a href="#">user1</a></span>
                            <i class="info-arrow info-arrow__right"></i>
                        </div>
                    </div>
                    <div class="waterfall-imgbox waterfall-box"><a href="#"><img
                            src="{% static 'myweb/index/images/cont/waterfall_imgB.jpg' %}" alt="#"></a></div>
                    <div class="waterfall-imgbox waterfall-box">
                        <a href="#"><img src="{% static 'myweb/index/images/cont/waterfall_imgC.jpg' %}" alt="#"></a>
                        <div class="waterfall-collect">
                        </div>
                    </div>
                </div>
            </div>
            <div style="display: block;
              padding: 10px;
              text-align: center;
              margin: 0 auto;
              width: 49%;
              font-size: 20px;
              color: #ffffff;
              background-color: #af1c09;">
                <a href="{% url 'myweb_index_login' %}">点击登录进入本站</a>
            </div>
            <div style="display: block;
              padding: 10px;
              text-align: center;
              margin: 0 auto;
              width: 49%;
              font-size: 20px;
              color: #00ff0d;
              background-color: #00ff3c;">
                <a href="{% url 'myweb_index_register' %}">点击注册账号</a>
            </div>
        </div>
        <div class="main-category">
            <div class="head clearfix">
                <span>分类浏览</span>
            </div>
            <div class="cont clearfix">
                <ul class="main-category__group">
                    <li class="item"><a href="#">运动</a></li>
                    <li class="item"><a href="#">旅游</a></li>
                    <li class="item"><a href="#">影视</a></li>
                </ul>
                <ul class="main-category__group">
                    <li class="item"><a href="#">工作</a></li>
                    <li class="item"><a href="#">英语学习</a></li>
                    <li class="item"><a href="#">国外旅游</a></li>
                </ul>
                <ul class="main-category__group">
                    <li class="item"><a href="#">读书</a></li>
                    <li class="item"><a href="#">情感分析</a></li>
                    <li class="item"><a href="#">星座运势</a></li>

                </ul>
                <ul class="main-category__group">
                    <li class="item"><a href="#">乐器</a></li>
                    <li class="item"><a href="#">游戏</a></li>
                    <li class="item"><a href="#">智力</a></li>
                </ul>
                <ul class="main-category__group">
                    <li class="item"><a href="#">拍照</a></li>
                    <li class="item"><a href="#">书法</a></li>
                    <li class="item"><a href="#">等等</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<footer style="width: 100%;
    height: 60px;
    line-height: 60px;
    text-align: center;
    color: #999;
    background-color: #000;">

    <div style="width: 100%;
    height: 80px;
    line-height: 60px;
    text-align: center;
    color: #d2c3c3;
    background-color: rgba(59,87,199,0.51);">
        <p>南开大学滨海学院毕业设计</p>
    </div>
</footer>

<script src="{% static 'myweb/index/js/jquery.js' %}"></script>
<script src="{% static 'myweb/index/js/script.js' %}"></script>

</body>
</html>

templates/myweb/index/register.html
{% load static %}
<!DOCTYPE html>
 <html lang="en">

 <head>
     <meta charset="UTF-8">
     <title>register</title>
     <script src="{% static 'myadmin/local/js/html5shiv.min.js'%}"></script>
     <script src="{% static 'myadmin/local/js/respond.min.js'%}"></script>
     <style>
         * {
             margin: 0;
             padding: 0;
         }

         html {
             height: 100%;
             width: 100%;
             overflow: hidden;
             margin: 0;
             padding: 0;
             background: url('/static/banckground/bgm1.jpg') no-repeat 1px 1px;
             background-repeat: no-repeat;
             background-size: 100% 100%;
             -moz-background-size: 100% 100%;
         }

         body {
             display: flex;
             align-items: center;
             justify-content: center;
             height: 100%;
         }

         #loginDiv {
             width: 37%;
             display: flex;
             justify-content: center;
             align-items: center;
             height: 650px;
             background-color: rgba(75, 81, 95, 0.3);
             box-shadow: 7px 7px 17px rgba(52, 56, 66, 0.5);
             border-radius: 5px;
         }

         #name_trip {
             margin-left: 50px;
             color: red;
         }

         p,
         .sexDiv {
             margin-top: 10px;
             margin-left: 20px;
             color: azure;
         }

         .sexDiv>input,
         .hobby>input {
             width: 30px;
             height: 17px;
         }

         input,
         select {
             margin-left: 15px;
             border-radius: 5px;
             border-style: hidden;
             height: 30px;
             width: 140px;
             background-color: rgba(216, 191, 216, 0.5);
             outline: none;
             color: #f0edf3;
             padding-left: 10px;
         }

         .button {
             border-color: cornsilk;
             background-color: rgba(100, 149, 237, .7);
             color: aliceblue;
             border-style: hidden;
             border-radius: 5px;
             width: 100px;
             height: 31px;
             font-size: 16px;
         }

         .introduce {
             margin-left: 110px;
         }

         .introduce>textarea {
             background-color: rgba(216, 191, 216, 0.5);
             border-style: hidden;
             outline: none;
             border-radius: 5px;
         }

         h1 {
             text-align: center;
             margin-bottom: 20px;
             margin-top: 20px;
             color: #f0edf3;
         }

         b {
             margin-left: 50px;
             color: #FFEB3B;
             font-size: 10px;
             font-weight: initial;
         }
     </style>
 </head>

 <body>
     <div id="loginDiv">
         <form action="{% url 'myweb_index_insert' %}" method="post" enctype="multipart/form-data">
             {% csrf_token %}
             <h1>注册用户</h1>
             <p>用户昵称:<input type="text" name ="nickname" id="inputText1"
                                           placeholder="用户昵称"/>

             <p>用户手机:<input name ="mobile" type="text" id="inputText2"
                                           placeholder="用户手机" />
             
             <p>用户邮箱:<input name="email" type="text" id="inputText3"
                                           placeholder="email"/>

             <p>用户密码:<input name="pass" type="password" id="inputText4"
                                           placeholder="用户密码"/>
             <div class="form-group">
             <p>头像：<input type="file" name="picture" id="id_picture"></p>
             </div>
             <p style="text-align: center;">
                 <button type="submit" class="button">提交</button>
                 <button type="reset" class="button">重置</button>
             </p>
         </form>
     </div>
<script src="{% static 'myadmin/bower_components/jquery/dist/jquery.min.js'%}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'myadmin/bower_components/bootstrap/dist/js/bootstrap.min.js'%}"></script>
<!-- AdminLTE App -->
<script src="{% static 'myadmin/dist/js/adminlte.min.js'%}"></script>

<script src="{% static 'myadmin/dist/js/edu-modal-alert-confirm.js'%}"></script>
 </body>

 </html>