date/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('myweb.urls')),  # 默认访问的登录界面
    path('myadmin/', include('myadmin.urls')),  # 后台管理

]

myweb/urls.py
# 前端子路由配置
from django.urls import path

from myweb.views import index
from myweb.views import home
urlpatterns = [
    path('', index.index, name="myweb_index"),
    path('index/login' , index.login , name="myweb_index_login") ,
    path('index/register',index.register,name="myweb_index_register"),#注册
    path('index/insert',index.insert,name="myweb_index_insert"),#执行注册
    path('index/dologin' , index.dologin , name="myweb_index_dologin") ,
    path('index/logout' , index.logout , name="myweb_index_logout") ,
    path('index/verify' , index.verify , name="myweb_index_verify") ,  # 验证码
    #主页面
    path('home',home.home,name='myweb_home'),
    #文章展示页面
    path('home/article/<int:aid>',home.article,name="myweb_home_article"),
    #发布文章页面
    path('home/addarticle',home.addarticle,name="myweb_home_addarticle"),
    #文章删除
    path('article_del',home.article_del,name="article_del"),
    #点赞
    path('aup',home.aup,name="aup"),
    #收藏
    path('collect',home.collect,name="collect"),
    #取消收藏
    path('c_del',home.c_del,name="c_del"),
    #收藏展示页面
    path('home/collection/<int:wid>',home.collection,name="myweb_home_collection"),
    #发表评论
    path('commit',home.commit,name="commit"),
    #删除评论
    path('del_commit',home.del_commit,name="del_commit"),
    #执行添加文章
    path('home/insertarticle',home.insertarticle,name="myweb_home_insertarticle"),
    #个人页面展示
    path('home/persional/<int:wid>',home.persional,name="myweb_home_persional"),
    #分类主页面
    path('home/cat/<int:wid>',home.cat,name="myweb_home_cat"),
    #个人信息页面
    path('home/edit',home.edit,name="myweb_home_edit"),
    #执行编辑
    path('home/update/<int:wid>',home.update,name="myweb_home_update"),
    # 个人简介
    path('home/editinfo' , home.editinfo , name="myweb_home_editinfo") ,
    # 执行编辑简介内容
    path('home/updateinfo/<int:wid>' , home.updateinfo , name="myweb_home_updateinfo") ,

]

myadmin/models.py
from datetime import datetime

from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
  #用户账号信息模型

class User(models.Model):
    username = models.CharField(max_length=50)    #用户账号
    nickname = models.CharField(max_length=50)    #昵称
    password_hash = models.CharField(max_length=100)  #密码
    password_salt = models.CharField(max_length=50)    #密码干扰值
    status = models.IntegerField(default=1)    #状态:1正常/6.管理员/2禁用/9删除
    create_at = models.DateTimeField(default=datetime.now)    #创建时间
    update_at = models.DateTimeField(default=datetime.now)    #修改时间

    def toDict(self):
        return {'id':self.id,'username':self.username,'nickname':self.nickname,'password_hash':self.password_hash,'password_salt':self.password_salt,'status':self.status,'create_at':self.create_at.strftime('%Y-%m-%d %H:%M:%S'),'update_at':self.update_at.strftime('%Y-%m-%d %H:%M:%S')}

    class Meta:
        db_table = "user"  # 表名

class Blog(models.Model):
    nid=models.AutoField(primary_key=True)
    title=models.CharField(max_length=64)
    site_name=models.CharField(max_length=32)
    theme=models.CharField(max_length=64)
    def toDict(self):
        return {'title':self.title}
    class Meta:
        db_table="blog"

#分类表
class Category(models.Model):
    nid = models.AutoField(primary_key=True)
    title=models.CharField(max_length=64)
    blog=models.ForeignKey(to=Blog,to_field='nid',null=True,on_delete=models.CASCADE)
    def toDict(self):
        return {'title':self.title}
    class Meta:
        db_table="category"
#标签
class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title=models.CharField(max_length=64)
    blog=models.ForeignKey(to=Blog,to_field='nid',null=True,on_delete=models.CASCADE)
    def toDict(self):
        return {'title':self.title}
    class Meta:
        db_table = "tag"  # 更改表名
#前端用户信息表
class Webuser(models.Model):
    nickname = models.CharField(max_length=50)
    head = models.CharField(max_length=255)
    mobile = models.CharField(max_length=50)
    password = models.CharField(max_length=50,null=True,blank=True)
    email = models.CharField(max_length=50)
    status = models.IntegerField(default=1)
    blog = models.OneToOneField(to=Blog,to_field='nid',null=True,on_delete=models.CASCADE)
    create_at = models.DateTimeField(default=datetime.now)
    update_at = models.DateTimeField(default=datetime.now)

    def toDict(self):
        return {'id':self.id,'blog':self.blog,'nickname':self.nickname,'head':self.head,'mobile':self.mobile,'head':self.head,'password':self.password,'status':self.status,'create_at':self.create_at.strftime('%Y-%m-%d %H:%M:%S'),'update_at':self.update_at.strftime('%Y-%m-%d %H:%M:%S')}

    class Meta:
        db_table = "webuser"  # 更改表名

#文章信息模型
class Article(models.Model):
    name = models.CharField(max_length=255)        #文章名称
    picture = models.CharField(max_length=255)  #封面图片
    main = models.CharField(max_length=255,null=True,blank=True)   #主要内容
    message = models.TextField()    #文章内容
    title = models.CharField(max_length=255)    #话题
    title_id = models.CharField(max_length=255)    #话题编号
    status = models.IntegerField(default=1)        #状态:1正常/2暂停/3删除
    publish_at = models.DateTimeField(default=datetime.now)    #发布时间
    up_num = models.IntegerField(default=0)                   #点赞数
    down_num = models.IntegerField(default=0)                     #收藏数
    blog = models.ForeignKey(to=Blog,to_field='nid',null=True,on_delete=models.CASCADE)
    category = models.ForeignKey(to=Category,to_field='nid',null=True,on_delete=models.CASCADE)
    tag = models.ManyToManyField(to=Tag , through='ArticleTOTag' , through_fields=('article','tag'))
    def toDict(self):
        articlename = self.name.split("-")
        return {'id':self.id,'name':articlename[0],'blog':self.blog,'category':self.category,'tag':self.tag,'picture':self.picture,'message':self.message,'title':self.title,'title_id':self.title_id,'status':self.status,'publish_at':self.publish_at.strftime('%Y-%m-%d %H:%M:%S'),'up_num':self.up_num,'webuser':self.webuser}

    class Meta:
        db_table = "article"  # 表名

class ArticleTOTag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to=Article,to_field='id',on_delete=models.CASCADE)
    tag = models.ForeignKey(to=Tag,to_field='nid',on_delete=models.CASCADE)


class Commit(models.Model):
    nid = models.AutoField(primary_key=True)
    webuser = models.ForeignKey(to='Webuser' , to_field='id',on_delete=models.CASCADE)
    article = models.ForeignKey(to='Article' , to_field='id',on_delete=models.CASCADE)
    content = models.CharField(max_length=255)
    publish_at = models.DateTimeField(default=datetime.now)
    parent = models.ForeignKey(to='self',to_field='nid',on_delete=models.CASCADE,null=True,blank=True)
    class Meta:
        db_table = "commit"  # 更改表名
#点赞
class UpAndDown(models.Model):
    nid = models.AutoField(primary_key=True)
    webuser = models.ForeignKey(to=Webuser,to_field='id',on_delete=models.CASCADE)
    article = models.ForeignKey(to=Article,to_field='id',on_delete=models.CASCADE)
    up_down = models.BooleanField()

    class Meta:
        unique_together=(("webuser","article"),)   #联合

#收藏
class Collect(models.Model):
    nid = models.AutoField(primary_key=True)
    webuser = models.ForeignKey(to=Webuser,to_field='id',on_delete=models.CASCADE)
    article = models.ForeignKey(to=Article,to_field='id',on_delete=models.CASCADE)
    up_down = models.BooleanField()

    class Meta:
        unique_together=(("webuser","article"),)   #联合

#个人简介及信息表
class Info(models.Model):
    id = models.AutoField(primary_key=True)
    webuser = models.ForeignKey(to='Webuser' , to_field='id' , on_delete=models.CASCADE)
    info = models.CharField(max_length=255)
    star = models.CharField(max_length=50)
    birth = models.DateTimeField(max_length=50,null=True)
    habit = models.CharField(max_length=255)
    school = models.CharField(max_length=127)
    location = models.CharField(max_length=127)

    class Meta:
        db_table = "info"  # 更改表名

myadmin/views/article.py
# 文章管理的视图文件
from django.http import HttpResponse , JsonResponse
from django.shortcuts import render
from django.core.paginator import Paginator
import time
from datetime import datetime

from myadmin.models import Article,Category,Blog


# 查看用户信息
def index(request , pIndex=1):
    '''浏览信息'''
    amod = Article.objects.get_queryset().order_by('id')
    mywhere = []
    alist = amod.filter(status__lt=3)

    # 获取、判断并封装关keyword键搜索
    kw = request.GET.get("keyword" , None)
    if kw:
        # 查询
        alist = alist.filter(name__contains=kw)
        mywhere.append("keyword=" + kw)

    # 获取、判断并封装状态status搜索条件
    status = request.GET.get('status' ,'')
    if status != '':
        alist = alist.filter(status=status)
        mywhere.append("status=" + status)

    # 执行分页处理
    pIndex = int(pIndex)
    page = Paginator(alist , 5)  # 以5条每页创建分页对象
    maxpages = page.num_pages  # 最大页数
    # 判断页数是否越界
    if pIndex > maxpages:
        pIndex = maxpages
    if pIndex < 1:
        pIndex = 1
    list2 = page.page(pIndex)  # 当前页数据
    plist = page.page_range  # 页码数列表

    # list2 = User.objects.all() #获取所有信息
    # 封装信息加载模板输出
    context = {"articlelist": list2 , 'plist': plist , 'pIndex': pIndex , 'maxpages': maxpages , 'mywhere': mywhere}
    return render(request , "myadmin/article/index.html" , context)


    # 增加用户信息
def add(request):
    ctype = Category.objects.all()
    btype = Blog.objects.all()
    context = {"ctype":ctype,"btype":btype}
    return render(request, 'myadmin/article/add.html',context)


def insert(request):
    '''执行添加'''
    try:
        #上传图片操作
        # 图片的上传处理
        myfile = request.FILES.get("picture", None)
        if not myfile:
            return HttpResponse("没有封面上传文件信息")
        picture = str(time.time()) + "." + myfile.name.split('.').pop()
        destination = open("./static/uploads/article/" + picture, "wb+")
        for chunk in myfile.chunks():  # 分块写入文件
            destination.write(chunk)
        destination.close()
        #封装
        ob = Article()
        ob.message = request.POST['message']
        ob.picture = picture
        ob.name = request.POST['name']
        ob.main = request.POST['main']
        ob.blog_id = request.POST['blog']
        ob.category_id = request.POST['category']
        ob.status = 1
        ob.publish_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ob.save()
        context = {"info": "添加成功！"}
    except Exception as err:
        print(err)
        context = {"info": "添加失败"}
    return render(request, "myadmin/info.html", context)

def delete(request,nid):
    '''删除信息'''
    try:
        ob = Article.objects.get(id=nid)
        ob.delete()
        context={"info":"删除成功！"}
    except Exception as err:
        print(err)
        context={"info":"删除失败"}

    return render(request,"myadmin/info.html",context)


def edit(request, nid):
    ctype = Category.objects.all()
    btype = Blog.objects.all()
    '''加载编辑信息页面'''
    try:
        ob = Article.objects.get(id=nid)
        context = {"article": ob,"ctype":ctype,"btype":btype}
        return render(request, "myadmin/article/edit.html", context)
    except Exception as err:
        context = {"info": "没有找到要修改的信息！"}
        return render(request, "myadmin/info.html", context)


def update(request, nid):
    '''执行编辑信息'''
    try:
        ob = Article.objects.get(id=nid)
        ob.status = request.POST['status']
        ob.blog_id = request.POST['blog']
        ob.category_id = request.POST['category']
        ob.update_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ob.save()
        context = {"info": "修改成功！"}
    except Exception as err:
        print(err)
        context = {"info": "修改失败"}
    return render(request, "myadmin/info.html", context)

myweb/views/index.py
import time
from datetime import datetime

from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.
from django.urls import reverse

from myadmin.models import Webuser , Blog , Info


def index(request):
    return render(request, 'myweb/index/index.html')

def login(request):
    return render(request , 'myweb/index/login.html')
#注册页面
def register(request):
    return render(request,'myweb/index/register.html')
#执行注册
def insert(request):
    '''执行添加'''
    try:
        # 图片的上传处理
        myfile = request.FILES.get("picture", None)
        if not myfile:
            return HttpResponse("没有头像上传文件信息")
        picture = str(time.time()) + "." + myfile.name.split('.').pop()
        destination = open("./static/uploads/webuser/" + picture, "wb+")
        for chunk in myfile.chunks():  # 分块写入文件
            destination.write(chunk)
        destination.close()
        #创建论坛
        obj = Blog()
        obj.title = request.POST['nickname']
        obj.theme = ''
        obj.site_name = ''
        obj.save()
        #增加用户
        ob = Webuser()
        ob.nickname = request.POST['nickname']
        ob.head = picture
        ob.mobile = request.POST['mobile']
        ob.email = request.POST['email']
        ob.password = request.POST['pass']
        ob.status = 1
        ob.create_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ob.update_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ob.blog = obj
        ob.save()
        #增加info
        obk = Info()
        obk.info = '暂无'
        obk.star = '暂无'
        obk.habit = '暂无'
        obk.location = '暂无'
        obk.school = '暂无'
        obk.birth = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        obk.webuser = ob
        obk.save()
        context = {"info": "注册成功！"}
    except Exception as err:
        print(err)
        context = {"info": "注册失败"}
    return render(request, "myweb/index/login.html", context)
#执行登录
def dologin(request):
    try:
        # 验证判断
        verifycode = request.session['verifycode']
        code = request.POST['code']  # 获取从前端获取的code值
        if verifycode != code:
            context = {'info': '验证码错误！'}
            return render(request , "myweb/index/login.html" , context)
        # 根据登录账号获取用户信息
        webuser = Webuser.objects.get(email=request.POST['email1'])
        # 校验当前用户状态是否可用
        if webuser.status == 1:
            n = webuser.password
            s = request.POST['pass']
            # 校验密码是否正确
            if n == s:
                # 将当前登录成功用户信息以adminuser这个key放入到session中
                request.session['webuser'] = webuser.toDict()
                return redirect(reverse('myweb_home'))
            else:
                context = {"info": "登录密码错误！"}
        else:
            context = {"info": "此用户非可用账号"}
    except Exception as err:
        print(err)
        context = {"info": "登录账号不存在！"}
    return render(request , "myweb/index/login.html", context)

#退出
def logout(request):
    del request.session['webuser']
    return redirect(reverse('myweb_index'))
#验证码
def verify(request):
    # 引入随机函数模块
    import random
    from PIL import Image , ImageDraw , ImageFont
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (242 , 164 , 247)
    width = 100
    height = 25
    # 创建画面对象
    im = Image.new('RGB' , (width , height) , bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制
    for i in range(0 , 100):
        xy = (random.randrange(0 , width) , random.randrange(0 , height))
        fill = (random.randrange(0 , 255) , 255 , random.randrange(0 , 255))
        draw.point(xy , fill=fill)
    # 定义验证码的取值
    str1 = '0123456789'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0 , 4):
        rand_str += str1[random.randrange(0 , len(str1))]
    # 字体属性
    font = ImageFont.truetype('static/AGENCYB.TTF' , 21)
    # 设置字体颜色
    fontcolor = (255 , random.randrange(0 , 255) , random.randrange(0 , 255))
    # 绘制4个字
    draw.text((5 , -3) , rand_str[0] , font=font , fill=fontcolor)
    draw.text((25 , -3) , rand_str[1] , font=font , fill=fontcolor)
    draw.text((50 , -3) , rand_str[2] , font=font , fill=fontcolor)
    draw.text((75 , -3) , rand_str[3] , font=font , fill=fontcolor)
    # 释放画笔
    del draw
    # 存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    # 内存文件操作
    import io
    buf = io.BytesIO()
    # 将图片保存在内存中
    im.save(buf , 'png')
    # 将内存中的图片数据返回给客户端
    return HttpResponse(buf.getvalue() , 'image/png')

templates/myweb/home/article.html
{% extends 'myweb/home/base.html' %}
{% block content %}
    <div>
        <div>
            <h1>{{ article.name }}</h1>
        </div>
        <div>
            <img class="media-object"
                 src="/static/uploads/article/{{ article.picture }}" width="900">
        </div>
        <div><h4>{{ article.message }}</h4></div>
        <div>
            <span>作者：{{ article.blog.webuser.nickname }}</span>
            <span>发布于：{{ article.publish_at|date:'Y-m-d H-i-s' }}</span>&nbsp;&nbsp;&nbsp;&nbsp;
            <span class="glyphicon glyphicon-comment">评论({{ article.commit_set.count }})</span>&nbsp;&nbsp;
            <span><button class="glyphicon glyphicon-hand-right aup"></button>点赞：({{ article.up_num }})</span>&nbsp;&nbsp;
            <span><button class="glyphicon glyphicon-heart a_collect"></button>收藏：({{ article.down_num }})</span>
        </div>
        <!-- 评论模块 -->
        <p></p>
        <div>
            <!-- 评论列表 -->
            <p style="font-weight:bold">评论列表</p>
        <ul class="list-group">
            {% for vo in commit_list %}
                <li class="list-group-item" style="width: 800px;height: auto">
                    <div class="media-left media-middle">
                        <a href="#">
                            <img class="img-circle"
                                 src="/static/uploads/webuser/{{ vo.webuser.head }}" alt="头像" width="50px" height="50px">
                            <span>{{ vo.webuser.nickname }}:</span>
                        </a>
                    </div>
                    <div class="media-body">
                        {% if vo.parent %}
                            <p class="well-sm">@{{ vo.webuser.nickname }}:{{ vo.parent.content }}</p>
                        {% endif %}
                        {{ vo.content }}
                        <span class="pull-right" style="font-size: smaller">时间：{{ vo.publish_at|date:"Y-m-d H-s" }}</span>
                        <a><span class="pull-right reply" username="{{ vo.webuser.nickname }}" commit_id="{{ vo.nid }}">回复&nbsp;&nbsp;</span></a>
                        {% if vo.webuser_id == request.session.webuser.id %}
                            <a class="del" type="submit" del_id="{{ vo.nid }}"><span class="pull-right">删除&nbsp;&nbsp;</span></a>
                        {% endif %}
                    </div>
                </li>
            {% endfor %}
        </ul>
        </div>
        <div>
            <!--发表评论-->
            <p style="font-weight: bold">发表评论</p>
            <div class="row">
                <div class="col-lg-6">
                    <div class="input-group" style="width: 800px">
                        <input type="text" class="form-control" id="id_content" style="height: 50px" placeholder="在此发布评论">
                        <span class="input-group-btn">
                                <button class="btn btn-default" id="btn_submit" style="height: 50px" type="button">提交</button>
                        </span>
                    </div><!-- /input-group -->
                </div><!-- /.col-lg-6 -->
            </div><!-- /.row -->
        </div>
        <div>

        </div>

    </div>
    <script>
    var parent_id=''
        //删除评论
        $(".del").click(function () {
            var del_id = $(this).attr('del_id')
            $.ajax({
                url:'/del_commit',
                type:'post',
                data:{del_id:del_id,csrfmiddlewaretoken: '{{ csrf_token }}'},
                success:function (data){
                    $("#id_content").val("")
                }
            })
        })
        //回复
        $(".reply").click(function (){
            var username=$(this).attr('username')
            parent_id=$(this).attr('commit_id')
            $("#id_content").focus()
            $("#id_content").val('@'+username+'  ')
        })
        //评论
        $("#btn_submit").click(function (){
            var content=$("#id_content").val()
            if(parent_id){
                var index=content.indexOf(' ')+1
                content=content.slice(index)
            }
            $.ajax({
                url:'/commit',
                type:'post',
                data:{article_id:'{{ article.id }}',content:content,webuser_id:'{{ request.session.webuser.id }}',csrfmiddlewaretoken: '{{ csrf_token }}',parent_id:parent_id},
                success:function (data){
                    $("#id_content").val("")
                }
            })
        })
        //点赞数据传输
        $(".aup").click(function (){
            var up_num=1
            //alert(up_num)
            $.ajax({
                url:'/aup',
                type:'post',
                data:{article_id: '{{article.id}}',up_num:up_num,webuser_id:'{{ request.session.webuser.id }}',csrfmiddlewaretoken: '{{ csrf_token }}'},
                success:function (data){
                    console.log(data)
                }
            })
        })
        //收藏数据
        $(".a_collect").click(function (){
            var up_num=1
            //alert(up_num)
            $.ajax({
                url:'/collect',
                type:'post',
                data:{article_id: '{{article.id}}',up_num:up_num,webuser_id:'{{ request.session.webuser.id }}',csrfmiddlewaretoken: '{{ csrf_token }}'},
                success:function (data){
                    console.log(data)
                }
            })
        })

    </script>
{% endblock %}

templates/myweb/home/cat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>
    <link rel="stylesheet" href="/static/myweb/bootstrap/css/bootstrap.css">
    <script src="/static/myweb/bootstrap/js/jquery.js"></script>
    <script src="/static/myweb/bootstrap/js/bootstrap.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'myweb_home' %}">首页</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <h2 style="text-align: center">{{ cat }}类论坛</h2>
        </div>
    </div><!-- /.container-fluid -->
    <HR width=100% color=#987cb9 SIZE=1>
    <!-- 副导航条 -->
    <nav class="navbar navbar-inverse">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="width:180%; margin:0 auto;">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'myweb_home_cat' 1 %}">运动 <span class="sr-only">(current)</span></a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'myweb_home_cat' 5 %}">摄影</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'myweb_home_cat' 2 %}">影视 <span class="sr-only">(current)</span></a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'myweb_home_cat' 3 %}">音乐</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'myweb_home_cat' 6 %}">书籍 <span class="sr-only">(current)</span></a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'myweb_home_cat' 7 %}">游戏</a></li>
            </ul>
        </div><!-- /.navbar-collapse2 -->
    </nav>
    <HR width=100% color=#987cb9 SIZE=1>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-9 col-sm-push-3">
                {% for article in alist %}
                    <div style="margin-bottom: 40px">
                        <h4><a href="{% url 'myweb_home_article' article.id %}">{{ article.name }}</a></h4>
                        <div class="media">
                            <div class="media-left media-middle">
                                <a href="#">
                                    <img class="img-circle"
                                         src="/static/uploads/webuser/{{ article.blog.webuser.head }}" height="60px"
                                         width="60px">
                                </a>
                            </div>
                            <div class="media-body" style="width: 800px;height: auto;font-weight: bold;font-size: 15px">
                                {{ article.main }}
                                <a href="{% url 'myweb_home_article' article.id %}"><span
                                        style="text-align: end">【查看全文】</span></a>
                            </div>
                            <span>作者：<a href="">{{ article.blog.webuser.nickname }}</a></span>
                            <span> 发布于：{{ article.publish_at|date:'Y-m-d H-i-s' }} </span>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-comment">评论({{ article.commit_set.count }}) </span>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-hand-right">点赞:({{ article.up_num }})  </span>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-heart">收藏：({{ article.down_num }})</span>
                        </div>
                    </div>
                    <HR height="5px" width="80%" color=#987cb9 SIZE=3>
                {% endfor %}
            </div>

        </div>
    </div>
</nav>
</body>
</html>